DJANGOCMS_UNITEGALLERY_CONFIG = {
    'THUMBNAIL_ENABLED': True,
    'THUMBNAIL_MAX_WIDTH': 250,
    'THUMBNAIL_MAX_HEIGHT': 250,
    'THUMBNAIL_PRESERVE_RATIO': False,
    'USE_EASYTHUMBNAILS': False
}
