# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_unitegallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_unitegallery_gallery', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Stores an image source file.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='filer.Image', verbose_name='Photo'),
        ),
    ]
